# PROGRAM INFO
TOOL_NAME = 'wholly'
TOOL_VER = '1.0.0'

# PARSING
PARSE_CMD_BUILD_PKG = 'build'

# FILES AND DIRS PATHS
PATH_REPO_DIR = 'recipes'
PATH_BUILD_BASE_DIR = 'build-base'
PATH_TMP_DIR = 'tmp'
PATH_RECIPE_FILE = 'recipe.yml'
PATH_CONTENTS_FILE = 'contents.yml'
PATH_RES_DIR = 'resources'
PATH_TMP_CONTENTS_FILE = 'contents.tmp'

# CONTAINER CONFIG
RELEASE_DIRECTORY = '/release'


#logging
LOG_LEVEL = 'WHOLLY_LOG_LEVEL'
LOG_FILE = 'WHOLLY_LOG_FILE'
